add blog post about jenkins job builder
pulp/pulpproject.org pull request #73
Opened 2017-07-06 13:57 UTC by kdelee

Short demo of using docker to serve up local instance of Jenkins for development of jenkins-job-builder generated jobs.

Please let me know if there are any edits you would like me to make!

2017-07-06 13:58 UTC, kdelee commented
You can see it rendered on my fork: https://kdelee.github.io/pulpproject.org/2017/07/05/jenkins-job-builder/

2017-07-06 14:14 UTC, daviddavis requested changes
Looks great @kdelee. 👍 

A few small comments.

2017-07-06 14:14 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +replacement so that you might test multiple versions against multiple OS's, and
s/OS's/OSes/

2017-07-06 14:14 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +more over that these assets should be under version control. The good news is,
s/more over/moreover,/

2017-07-06 14:14 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +test it out: There is an official [Jenkins image on
I would probably change the colon here to a period maybe?

2017-07-06 14:14 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +I then visited the Jenkins web ui at <code>http://localhost:8080</code> and was directed to
s/ui/UI/

2017-07-06 14:14 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +password created printed to the logs. I created a new admin account and password and chose to
A bit of a run-on sentence. How about:

I then visited the Jenkins web UI at <code>http://localhost:8080</code> and was directed to login with an admin account created during the install. A temporary admin password could be found in the logs. 

Also, I'd probably drop "and password" here too. Too many ands.

2017-07-06 14:15 UTC, dralley reviewed
Thank you for this PR @kdelee !

This was very good, I only had a few nitpicks but no serious objections

2017-07-06 14:15 UTC, dralley commented on _posts/2017-07-05-jenkins-job-builder.md
> +I first was exposed to Jenkins when I was working for a open source software
"while working for" might sound better than "when I was working for"

2017-07-06 14:15 UTC, dralley commented on _posts/2017-07-05-jenkins-job-builder.md
> +set a critical value, perhaps creating a faulty job that leads to misleading
This sentence should probably be broken up a bit into two or three sentences

2017-07-06 14:15 UTC, dralley commented on _posts/2017-07-05-jenkins-job-builder.md
> +To scale the process of Jenkins job definition it become obvious that one must
s/become/became

This sentence needs to be broken up a bit or rewritten to be shorter/multiple sentences.

2017-07-06 14:16 UTC, daviddavis commented on _posts/2017-07-05-jenkins-job-builder.md
> +title: Introduction to Jenkins Job Builder
I might title this with something more specific like "Testing Jenkins Configurations with Jenkins Job Builder"

2017-07-07 13:50 UTC, kdelee commented
@daviddavis @dralley 

Thanks for the review, I have pushed those changes to the branch on this PR and you should be able to see them on my fork!

2017-07-07 18:55 UTC, daviddavis approved these changes

2017-07-07 18:59 UTC, dralley approved these changes

2017-07-10 14:01 UTC, merged